name: Deploy website

on:
  push:
      branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn
          yarn run lerna bootstrap
          yarn run lerna run build --scope=greenbox-web

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/greenbox-web/dist